# Generated by Django 5.1 on 2024-09-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_category_slug_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Фото для статті', 'verbose_name_plural': 'Фото для статті'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія для новини', 'verbose_name_plural': 'Категорія для новин'},
        ),
    ]
